In [ ]:
3.3.1. Introduction to KNN classification

In [1]:
'''
supervised learning:
    output predict on input
    inputs : Predictors, Independent Variables, Features, Variables
    outputs: Response variables, Dependent variables
    
Regression Problems : Quantitative response: number measures weight height 
Classification Problem  : Qualitative response: Y/N, Blue/Green

kNN : 
    1 approach to classification
    k = 5: 
        identify 5 data point near the data
        classify new data point as belonging to most common class among those neighbours

'''

'\nsupervised learning:\n    output predict on input\n    inputs : Predictors, Independent Variables, Features, Variables\n    outputs: Response variables, Dependent variables\n    \nRegression Problems : Quantitative response: number measures weight height \nClassification Problem  : Qualitative response: Y/N, Blue/Green\n\nkNN : \n    1 approach to classification\n    k = 5: \n        identify 5 data point near the data\n        classify new data point as belonging to most common class among those neighbours\n\n'

3.3.2 Finding the distance between two points

In [2]:
'''
(x1,y1) (x2,y2) 
d2 = ((x2-x1)^2 + (y2-y1)^2)0.5
mathematics : numpy
'''

'\n(x1,y1) (x2,y2) \nd2 = ((x2-x1)^2 + (y2-y1)^2)0.5\nmathematics : numpy\n'

In [3]:
import numpy as np
p1 = np.array([1,1])
p2 = np.array([4,4])
p2-p1

array([3, 3])

In [4]:
np.power(p2-p1, 2)

array([9, 9], dtype=int32)

In [5]:
np.sqrt(np.sum(np.power(p2-p1, 2)))

4.242640687119285

In [6]:
import numpy as np

def distance(p1,p2):
    '''
    Find the distance between the points p1, p2
    '''
    return np.sqrt(np.sum(np.power(p2-p1, 2)))

In [7]:
p1 = np.array([1,1])
p2 = np.array([4,4])
distance(p1,p2)

4.242640687119285

3.3.3 Majority Vote

In [8]:
'''
KNN - Majority vote
Sequence of votes 
    - 1,2,3 : determine how many times each occured and find most common elements
    ex: 2 - 1's
        1 - 2's
        1 - 3's
        majority vote - 2
        
'''

"\nKNN - Majority vote\nSequence of votes \n    - 1,2,3 : determine how many times each occured and find most common elements\n    ex: 2 - 1's\n        1 - 2's\n        1 - 3's\n        majority vote - 2\n        \n"

In [9]:
def count_words(text):
    '''
    Count the number of times each word occures in text (str). skip punctuation
    Returns dictionary where keys are unique words and values are word counts.
    
    '''
    text=text.lower()
    
    skips = [".", ",", ":", ";", "'", '"']
    for ch in skips:
        text = text.replace(ch,"")
    
    word_counts = {}
    
    for word in text.split(" "):
        if word in word_counts:
            word_counts[word] += 1
        
        else:
            word_counts[word] = 1
            
    return word_counts

In [19]:
def majority_vote(votes):
    '''
    Return the most common element in votes
    
    '''
    vote_counts = {}
    
    for vote in votes:
        if vote in vote_counts:
            vote_counts[vote] += 1  
        else:
            vote_counts[vote] = 1
    
    return vote_counts

In [21]:
votes = [1,2,3,1,2,3,1,2,3,3,3,3]

vote_counts = majority_vote(votes)
vote_counts

{1: 3, 2: 3, 3: 6}


{1: 3, 2: 3, 3: 6}

In [22]:
max(vote_counts)

3

In [23]:
max(vote_counts.keys())

3

In [24]:
max(vote_counts.values())

6

In [26]:
max_counts = max(vote_counts.values())
max_counts

6

In [28]:
for vote, count in vote_counts.items():
    print(vote,count)

1 3
2 3
3 6


In [30]:
winners = []
max_counts = max(vote_counts.values())
for vote, count in vote_counts.items():
    if count == max_counts:
        winners.append(vote)
    
winners    

[3]

In [31]:
import random

def majority_vote(votes):
    '''
    Return the most common element in votes    
    '''
    vote_counts = {}
    
    for vote in votes:
        if vote in vote_counts:
            vote_counts[vote] += 1  
        else:
            vote_counts[vote] = 1
    
    winners = []
    max_counts = max(vote_counts.values())
    for vote, count in vote_counts.items():
        if count == max_counts:
            winners.append(vote)
    
    return random.choice(winners)

In [35]:
votes = [1,2,3,1,2,3,1,2,3,3,3,3]

winner = majority_vote(votes)
winner

3

In [36]:
votes = [1,2,3,1,2,3,1,2,3,3,3,3,2,2,2]

3

In [37]:
winner = majority_vote(votes)
winner

3

In [38]:
winner = majority_vote(votes)
winner

2

In [41]:
'''
most commonly occured element in the sequence - mode
'''

import scipy.stats as ss

def majority_vote_short(votes):
    '''
    Return the most common element in votes
    '''
    mode, count = ss.mstats.mode(votes)
    return mode

In [43]:
votes = [1,2,3,1,2,3,1,2,3,3,3,3]

majority_vote_short(votes)

array([3.])

In [45]:
votes = [1,2,3,1,2,3,1,2,3,3,3,3,2,2,2]

majority_vote_short(votes)

array([2.])