# 2.1.1 Scope Rules

In [1]:
'''
    inner to outer layer
    L - Local
    E - Enclosing functions
    G - Global
    B - Built in
      - Raise Name Error if couldnt find
      
'''

'\n    inner to outer layer\n    L - Local\n    E - Enclosing functions\n    G - Global\n    B - Built in\n      - Raise Name Error if couldnt find\n      \n'

In [2]:
def update():
    x.append(1)

In [3]:
x = [1,1] #global declaration - L E G B

In [4]:
update()

In [5]:
x

[1, 1, 1]

In [6]:
def update(n,x):
    n=2 #local variable - L E G B - created and deleted inside function
    x.append(4)
    print('update: ',n,x)

In [7]:
def main():
    n=1
    x=[0,1,2,3]
    print('main1: ',n,x)
    update(n,x)
    print('main1: ',n,x)

In [8]:
main()

main1:  1 [0, 1, 2, 3]
update: 2 [0, 1, 2, 3, 4]
main1:  1 [0, 1, 2, 3, 4]


In [4]:
def increment(n):
    n += 1 
    print(n)

In [6]:
n=1
increment(n)
print(n)

2
1


In [12]:
def increment(n):
    n += 1
    return n #code to print out pust for below code as 10 

In [13]:
n = 1
while n < 10:
    n = increment(n)
print(n)

10


# 2.1.2 Classes and Object Oriented Programming

In [14]:
'''
Python mainly used for functional programming approach
object 
    - data
    - methods
    
    Built in types
    - Lists
    - dictionaries
    
    Class:
    - if Built in object not solving the purpose
    - class: blueprint, instance: outside class defination
    - are of new object type
    - if resembles existing object types can be inherited
    - Ex: List plus additional method
'''

'\nPython mainly used for functional programming approach\nobject \n    - data\n    - methods\n    \n    Built in types\n    - Lists\n    - dictionaries\n    \n    Class\n    -if Built in object not solving the purpose\n    - are of new object type\n    - if resembles existing object types can be inherited\n    - Ex: List plus additional method\n'

In [19]:
x = [5,9,3,6,8,11,4,2]

In [20]:
x.sort()
x

[2, 3, 4, 5, 6, 8, 9, 11]

In [21]:
min(x)

2

In [22]:
max(x)

11

In [23]:
x.remove(9)

In [24]:
x

[2, 3, 4, 5, 6, 8, 11]

In [28]:
#class mylist inherited from list - list attribute + own
class MyList(list):
    def remove_min(self): #instance method
        # self is 1st argument in inheritance.  self refers to the instance on which operation is performed.
        self.remove(min(self))
        
    def remove_max(self): #instance method
        self.remove(max(self))

In [29]:
x = [5,9,3,6,8,11,4,2]

In [31]:
y = MyList(x)

In [32]:
dir(x)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [33]:
dir(y) # Two methods are added :'remove_max','remove_min' to list class

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'remove_max',
 'remove_min',
 'reverse',
 'sort']

In [35]:
y.remove_min()
y

[5, 9, 6, 8, 11, 4]

In [37]:
y.remove_max()
y

[5, 6, 8, 4]

In [38]:
class NewList(list):
    def remove_max(self):
        self.remove(max(self))
    def append_sum(self):
        self.append(sum(self))

In [39]:
x = NewList([1,2,3])
while max(x) < 10:
    x.remove_max()
    x.append_sum()

print(x)

KeyboardInterrupt: 

# 2.2.1: Introduction to NumPy Arrays

In [40]:
'''
Numpy Array
    - Scientific and Numberic computation
    - Undimensional array
    - can integrate with : c, c++, fortron
    - operations like linear algebra, random number
    - Numpy.org
    - Additional array dataTypes 
        vectors
        matrix
    - Numpy array 
        are fixed size when constructed.
        elements are of same dT - default type: float
        so, more efficient and simpler
'''

'\nNumpy Array\n    - Scientific and Numberic computation\n    - Undimensional array\n    - can integrate with : c, c++, fortron\n    - operations like linear algebra, random number\n    - Numpy.org\n    - Additional array dataTypes \n        vectors\n        matrix\n    - Numpy array \n        are fixed sizze when constructed.\n        elements are of same dT - default type: float\n        so, more efficient and simpler\n'

In [42]:
import numpy as np

In [44]:
zero_vectors = np.zeros(5)
zero_vectors

array([0., 0., 0., 0., 0.])

In [46]:
zero_matrix = np.zeros((2,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
one_vectors = np.ones(5)
one_vectors

array([1., 1., 1., 1., 1.])

In [49]:
zero_matrix = np.ones((2,3))
zero_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
# empty : Return a new array of given shape and type, without initializing entries.
empty_vectors = np.empty(0)
print('np.empty(0)',empty_vectors)
empty_vectors = np.empty(2)
print('np.empty(2)',empty_vectors)
empty_vectors = np.empty(5)
print('np.empty(5)',empty_vectors)
empty_vectors = np.empty(3)
print('np.empty(3)',empty_vectors)

np.empty(0) []
np.empty(2) [5.16690004e-186 2.18611321e+304]
np.empty(5) [1. 1. 1. 1. 1.]
np.empty(3) [7.67112743e+170 1.99631797e+161 7.20185273e+159]


In [64]:
import numpy as geek 
  
b = geek.empty(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = geek.empty([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = geek.empty([3, 3]) 
print("\nMatrix c : \n", c) 

d = geek.empty(5) 
print("Matrix d : \n", d)

e = geek.empty(5, dtype = int) 
print("Matrix e : \n", e)

Matrix b : 
 [5 0]

Matrix a : 
 [[-1448361029   427195210]
 [  891255793  2132795617]]

Matrix c : 
 [[1.58101007e-322 4.36754031e-321 2.47032823e-323]
 [3.75273134e-316 0.00000000e+000 3.23815565e-319]
 [3.74311801e-316 0.00000000e+000 2.47032823e-323]]
Matrix d : 
 [1. 1. 1. 1. 1.]
Matrix d : 
 [ 544342494 1948280431 1679844712 1869046121  543973742]


In [74]:
#construct array: np.array()
x = np.array([1,2,3]) # vector : small letter -  x
y = np.array([2,4,6])

In [77]:
A = np.array([[1,3],[5,9]]) #matrix: Capital letter
A

array([[1, 3],
       [5, 9]])

In [76]:
#matrix transpose
A.transpose()

array([[1, 5],
       [3, 9]])

In [2]:
import numpy as np
x = np.array([1,2,3])
x.


AttributeError: 'numpy.ndarray' object has no attribute 'append'

# 2.2.2 Slicing Numpy Arrays

In [6]:
'''
    [:] all numbers in the array
    [1,] given row
'''

'\n    [:] all numbers in the array\n    [1,] given row\n'

In [7]:
import numpy as np
x = np.array([1,2,3])
y = np.array([2,4,6])

In [8]:
x[2]

3

In [9]:
x[0:2]

array([1, 2])

In [10]:
z=x+y
z

array([3, 6, 9])

In [11]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[2,4,6],[8,10,12]])

In [12]:
X[:,1] #all rows, 1st element

array([2, 5])

In [13]:
Y[:,1]

array([ 4, 10])

In [14]:
X[:,1] + Y[:,1]

array([ 6, 15])

In [15]:
X[1:,] #1st row and rest

array([[4, 5, 6]])

In [16]:
X[1:,] + Y[1:,]

array([[12, 15, 18]])

In [18]:
X[1]

array([4, 5, 6])

In [19]:
[2,4]+[6,8] # concatinate list

[2, 4, 6, 8]

In [20]:
type([2+4])

list

In [21]:
np.array([2,4]) + np.array([6,8]) # addition numpy array

array([ 8, 12])

In [22]:
x = np.array([1,2,5])
x[1:2]

array([2])

In [23]:
a = np.array([1,2])
b = np.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 